const mongoose = require('mongoose')

const OptionSchema = new mongoose.Schema({
  id: { type: Number, required: true },
  description: { type: String, required: true },
  question_id: { type: Number, required: true },
  is_correct: { type: Boolean, required: true },
  created_at: { type: Date, required: true },
  updated_at: { type: Date, required: true },
  unanswered: { type: Boolean, required: true },
  photo_url: { type: String, default: null },
})

const QuestionSchema = new mongoose.Schema({
  id: { type: Number, required: true },
  description: { type: String, required: true },
  difficulty_level: { type: String, default: null },
  topic: { type: String, required: true },
  is_published: { type: Boolean, required: true },
  created_at: { type: Date, required: true },
  updated_at: { type: Date, required: true },
  detailed_solution: { type: String },
  type: { type: String, default: '' },
  is_mandatory: { type: Boolean, required: true },
  show_in_feed: { type: Boolean, required: true },
  pyq_label: { type: String, default: null },
  topic_id: { type: Number, required: true },
  reading_material_id: { type: Number, required: true },
  fixed_at: { type: Date, default: null },
  fix_summary: { type: String, default: null },
  created_by: { type: String, default: null },
  updated_by: { type: String, default: null },
  quiz_level: { type: String, default: null },
  question_from: { type: String, required: true },
  language: { type: String, default: null },
  photo_url: { type: String, default: null },
  photo_solution_url: { type: String, default: null },
  is_saved: { type: Boolean, required: true },
  tag: { type: String, default: '' },
  options: [OptionSchema],
})

const QuizSchema = new mongoose.Schema({
  id: { type: Number, required: true },
  name: { type: String, default: null },
  title: { type: String, required: true },
  description: { type: String, default: '' },
  difficulty_level: { type: String, default: null },
  topic: { type: String, required: true },
  time: { type: Date, required: true },
  is_published: { type: Boolean, required: true },
  created_at: { type: Date, required: true },
  updated_at: { type: Date, required: true },
  duration: { type: Number, required: true },
  end_time: { type: Date, required: true },
  negative_marks: { type: Number, required: true },
  correct_answer_marks: { type: Number, required: true },
  shuffle: { type: Boolean, required: true },
  show_answers: { type: Boolean, required: true },
  lock_solutions: { type: Boolean, required: true },
  is_form: { type: Boolean, required: true },
  show_mastery_option: { type: Boolean, required: true },
  quiz_type: { type: String, default: null },
  is_custom: { type: Boolean, required: true },
  banner_id: { type: String, default: null },
  exam_id: { type: String, default: null },
  show_unanswered: { type: Boolean, required: true },
  ends_at: { type: Date, required: true },
  lives: { type: String, default: null },
  live_count: { type: String, required: true },
  coin_count: { type: Number, required: true },
  questions_count: { type: Number, required: true },
  daily_date: { type: String, required: true },
  max_mistake_count: { type: Number, required: true },
  questions: [QuestionSchema],
})

const QuizModel = mongoose.model('Quiz', QuizSchema)

module.exports = QuizModel
